10_Forms/solutions/shirts_app/config/routes.rb
ShirtsApp::Application.routes.draw do

  root 'shirts#index'
  resources :shirts

end

10_Forms/solutions/shirts_app/app/models/shirt.rb
class Shirt < ActiveRecord::Base
  validates :name, presence: true
  # validates :description, length: { minimum: 10 }


  def self.search_for(query)
    where('name LIKE :query OR description LIKE :query', query: "%#{query}%")
  end

end

10_Forms/solutions/shirts_app/app/controllers/shirts_controller.rb
class ShirtsController < ApplicationController
  before_action :load_shirt, only: [ :edit, :update, :show, :destroy ]

  def index
    @shirts = Shirt.search_for(params[:q])
  end

  def show
  end

  def edit
  end

  def new
    @shirt = Shirt.new
  end

  def update
    @shirt.update safe_shirt_params
    redirect_to @shirt
  end

  def create
    @shirt = Shirt.new(safe_shirt_params)
    if @shirt.save # valid!
      redirect_to @shirt  # shirt_path(@shirt)
    else # invalid!
      render 'new'
    end
  end

  def destroy
    @shirt.delete
    redirect_to shirts_path
  end

  private

  def safe_shirt_params
    params.require('shirt').permit(:name, :description, :image)
  end

  def load_shirt
    @shirt = Shirt.find(params[:id])
  end

end

10_Forms/solutions/shirts_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShirtsApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

10_Forms/solutions/shirts_app/app/views/shirts/_form.html.erb
<% if @shirt.errors.any? %>
  <h1>Errors:</h1>
  <ul>
    <% @shirt.errors.full_messages.each do |msg|%>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>


<%= form_for @shirt do |f| %>
<fieldset>
  <div class='fields'>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class='fields'>
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
  <div class='fields'>
    <%= f.label :image %>
    <%= f.text_field :image, placeholder: 'placehold this..' %>
  </div>
  <%= f.submit %>
</fieldset>
<% end %>

10_Forms/solutions/shirts_app/app/views/shirts/edit.html.erb
<h4>Edit Form:</h4>

<%= render 'form' %>

10_Forms/solutions/shirts_app/app/views/shirts/index.html.erb
<h2>See all the shirts!</h2>

<%= form_tag shirts_path, method: :get do %>
  <%= text_field_tag :q, params[:q]%>
  <%= submit_tag 'Search' %>
<% end %>

<br/>


<% @shirts.each do |shirt| %>
  <%= shirt.id %> ||
  <%= link_to shirt.name, shirt %>:
  <%= shirt.description %>
  <%= link_to '[ EDIT ]', edit_shirt_path(shirt) %><br/>

  <%= form_for shirt, method: :delete do |f|%>
    <%= f.submit 'Delete' %>
  <% end %>

<% end %>

10_Forms/solutions/shirts_app/app/views/shirts/new.html.erb
<h3>New Shirt</h3>

<%= render 'form' %>

10_Forms/solutions/shirts_app/app/views/shirts/show.html.erb
<%= @shirt.name %>